apiVersion: apps/v1
kind: Deployment
metadata:
  name: myinsuranceappduygu-deployment
  labels:
    app: myinsuranceappduygu
spec:
  replicas: 8
  selector:
    matchLabels:
      app: myinsuranceappduygu
  template:
    metadata:
      labels:
        app: myinsuranceappduygu
    spec:
      containers:
      - name: myinsuranceappduygu
        image: duygu.azurecr.io/myinsuranceappduygu:v8
        ports:
        - name: http
          containerPort: 5000