apiVersion: v1
kind: Service
metadata:
  name: myinsuranceappduygu-az
  labels:
    app: myinsuranceappduygu-az
spec:
  selector:
    app: myinsuranceappduygu-az
  type: NodePort
  ports:
  - port: 5000
    targetPort: http
    protocol: TCP
    name: http
