apiVersion: v1
kind: Service
metadata:
  name: myinsuranceappduygu
  labels:
    app: myinsuranceappduygu
spec:
  selector:
    app: myinsuranceappduygu
  type: NodePort
  ports:
  - port: 5000
    targetPort: http
    protocol: TCP
    name: http